### ISSUE TITLE
Add Tabs to switch between table views

### ISSUE THREAD

**Issue by tangjon** [tangyjon/OAS-System#9]

**Comment by tangjon** [comment]
```
            <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
            
              <div class="mdl-tabs__tab-bar">
                  <button id="show-add-member-form-btn" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">New Member</button>
                  
                <a id="all-tab" href="#all-tab" class="mdl-tabs__tab is-active">All</a>
                <a id="beaver-tab" href="#beaver-tab" class="mdl-tabs__tab">Beavers</a>
                <a id="cub-tab" href="#cub-tab" class="mdl-tabs__tab">Cubs</a>
                <a id="scout-tab" href="#scout-tab" class="mdl-tabs__tab">Scout</a>
              </div>

            </div>
```

**Comment by tangyjon** [comment]
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
            
              <div class="mdl-tabs__tab-bar">
                  <button id="show-add-member-form-btn" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">New Member</button>
                  
                <a id="all-tab" href="#all-tab" class="mdl-tabs__tab is-active">All</a>
                <a id="beaver-tab" href="#beaver-tab" class="mdl-tabs__tab">Beavers</a>
                <a id="cub-tab" href="#cub-tab" class="mdl-tabs__tab">Cubs</a>
                <a id="scout-tab" href="#scout-tab" class="mdl-tabs__tab">Scout</a>
              </div>

            </div>
